default_stages: [commit]


repos:

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-fix
        additional_dependencies: ['dbt-postgres==1.5.3', 'sqlfluff-templater-dbt']

  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.18.0
    hooks:
      - id: sqlfmt
        language_version: python