name: deploy

on:
  push:
    branches: ["master"]

jobs:
   build:
     runs-on: ubuntu-latest
     # env:
     #   DBT_USER: ${{secrets.DBT_USER}}
     #   DBT_PASS: ${{secrets.DBT_PASS}}
     #   DB_NAME: ${{secrets.DB_NAME}}
     #   DB_PORT: ${{secrets.DB_PORT}}
     steps:
      - name: Checkout_Repository
        uses: actions/checkout@v3
  
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          
    
