version: 2

sources:
  - name: spider
    description: Исходные данные проектов Spider Project. Названия колонок соответствуют кодам колонок из Spider Project
    schema: public
    database: oup
    tables:
      - name: raw_spider__gandoper
        description: Гантт работ с конфигурацией api_gandoper.
      - name: raw_spider__archive
        description: Архив исполнения с конфигурацией api_archive.
      - name: raw_spider__assign
        description: Назначения с конфигурацией api_assign.
      - name: raw_spider__cost
        description: Стоимостные составляющие с конфигурацией api_cost.
      - name: raw_spider__ganttmat
        description: Гантт материалов с конфигурацией api_ganttmat.
      - name: raw_spider__mult
        description: Мультиресурсы с конфигурацией api_mult.
      - name: raw_spider__periodmat
        description: Периоды материалов с конфигурацией api_periodmat.
      - name: raw_spider__periodres
        description: Периоды ресурсов с конфигурацией api_periodres.
      - name: raw_spider__res
        description: Ресурсы с конфигурацией api_res.
  - name: dicts
    schema: public
    database: oup
    tables:
      - name: dict__rus_months
        description: справочник названий месяцев на кириллице и кварталов, к которым относятся месяца
        columns:
        - name: num_month
          description: порядковый номер месяца
        - name: name_month
          description: месяц
        - name: quart
          description: квартал
      - name: dict__1c_objects_to_spider
        description: справочник для сопоставления названий объектов в 1С и Spider Project
        columns: 
          - name: territory_value
            description: уникальный код "территории" в 1С
          - name: territory_name
            description: название объекта в 1С
          - name: territory_name_spider_project
            description: название объекта в Spider Project
  - name: excel
    schema: public
    database: oup
    tables:
      - name: raw__vdc_by_objects
        description: Контрактные ведомости из excel по объектам
        columns:
        - name: object
          description: объект строительства
  - name: 1c
    schema: 1c
    database: oup
    tables: 
      - name: 1_c__materials
        description: Раздел с указанием фактического расхода материалов из документа ЖУФВР
      - name: 1_c__norm_workload
        description: Нормативная трудоемкость выполненных работ в разрезе ресурсов
      - name: 1_c__pikets
      - name: 1_c__technique_workers
        description: Фактические часы работы техники и рабочих. Является разделом (вкладкой) "Сводно по смене" из документа ЖУФВР
      - name: 1_c__works
        description: Выполненные работы по ЖУФВР
      - name: 1_c__zhufvr
models:
 - name: int__archive_by_month
   description: Операции из таблицы Архив исполнения в помесячной разбивке. 
                Если длительность выполнения операции выходит за пределы одного месяца, то эта длительность распределяется на несколько месяцев. Вес – это отношение длительности выполнения операции в пределах какого-либо месяца к общей длительности операции. Все показатели распределены по периодам (месяцам), а значения показателей определены с учетом веса. 
                Распределение длительности выполнения операции по месяцам осуществлены при помощи рекурсивного запроса. 
                Использован фильтр (WHERE "ZATRATY" IS NOT NULL or "PRIBYL" is not null or "SMRFull" is not null), чтобы оставить только ключевые значения.
   columns: 
     - name: smr_ss
       description: СМР собственные силы
     - name: smr_sp
       description: СМР субподрядчики
     - name: SMRFull
       description: стоимость проекта факт, т.е. сумма СМР собственные силы и СМР субподрядчики
     - name: ZATRATY
       description:  сумма всех затратных стоимостных составляющих
     - name: PRIBYL
       description: разность между доходной и расходной частью
 - name: int__gant_by_month
   description: Операции из таблицы Гантт операций в помесячной разбивке.
                Если длительность выполнения операции выходит за пределы одного месяца, то эта длительность распределяется на несколько месяцев. 
                Вес – это отношение длительности выполнения операции в пределах месяца к общей длительности операции. Все показатели распределены по периодам (месяцам), а значения показателей определены с учетом веса. 
                Распределение длительности выполнения операции по месяцам осуществлены при помощи рекурсивного запроса.
   columns: 
     - name: smr_ss
       description: СМР собственные силы
     - name: smr_sp
       description: СМР субподрядчики
     - name: SMRFull
       description: стоимость проекта план - СМР собственные силы + СМР субподрядчики
     - name: ZATRATY
       description: сумма всех затратных стоимостных составляющих согласно Нормам со знаком минус
     - name: PRIBYL
       description: разность между доходной частью и затратами
 - name: int__gant_start_transform
   description: Расчет даты начала операции в плане. 
                Если расчетная дата (окончание - длительность в днях) попадает на последний день месяца, то сдвигаем дату начала на первый день следующего месяца. 
                Чтобы исключить операции связанные с операциями с типом ДПГ = Переключатель, добавлено условие (WHERE "Fin" is not null). 
                Fin – дата и время окончания операции. 
   columns: 
     - name: dur_plan_d
       description: Длительность, Дни [План]
     - name: start_year
       description: Год начала в формате числа
     - name: start_month
       description: Месяц начала в формате числа 

 - name: int__vdc_by_objects
   description: ВДЦ всех действующих объектов, подготовленные для дальнейшего использования в расчетах.
                Столбец "Позиция из КВ" применятся для наглядной демонстрации названия работы вместе с номером контрактной позиции.
   columns: 
     - name: "СМР П"
       description: Цена работы (всего) из контрактной ведомости. Примечание':' в зависимости от объектов строительства название в контрактной ведомости может отличаться
     - name: "Позиция из КВ"
       description: объединение столбцов "Шифр единичной расценки" и "Наименование работ и затрат", и между ними 4 пробела. Применяется для наглядной демонстрации шифра и названия работы
     - name: unique_test
       description: объединение столбцов "Шифр единичной расценки" и "object", и между ними 4 пробела. Применяется в тесте на поиск повторяющихся контрактных позиций. Применены два теста':' 1) unique - значения столбца должны быть уникальными и 2) not_null - не NULL (не пустые)
       tests: 
         - unique 
         - not_null
 - name: mart__gant_archive_by_month
   description: Объединенные фактические и плановые показатели работ в помесячной разбивке
   columns:
     - name: ZATRATY 
       description: затратная часть
     - name: PRIBYL
       description: прибыль
     - name: SMRFull
       description: доходная часть
     - name: s_month
       description: месяц начала операции. С помощью условия добавлен 0 (ноль) перед номерами месяцев, состоящих из одной цифры. Это необходимо для построения графиков в Superset 
     - name: smr_type
       description: тип СМР - факт или план
     - name: Name
       description: название операции 
     - name: Ispol
       description: Исполнитель 
     - name: IspolUch
       description: Исполнитель [Строительные участки]
     - name: Силы реализации
       description: 
     - name: SNT_Knstr
       description: Конструктив
     - name: SNT_KnstrE
       description: Конструктивный элемент
     - name: SNT_TypeKnstrE
       description: Тип конструктивного элемента
     - name: SNT_Obj
       description: Объект строительства
     - name: Num_Con
       description: № п/п по контрактной ведомости
     - name: Конструктив
       description: Земляное полотно/Дорожная одежда/Прочие работы
