version: 2

sources:
  - name: spider
    schema: public
    database: oup
    tables:
      - name: raw_spider__gandoper
        description: таблица Гантт работ с конфигурацией api_gandoper. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__archive
        description: таблица Архив исполнения с конфигурацией api_archive. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__assign
        description: таблица Назначения с конфигурацией api_assign. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__cost
        description: таблица Стоимостные составляющие с конфигурацией api_cost. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__ganttmat
        description: таблица Гантт материалов с конфигурацией api_ganttmat. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__mult
        description: таблица Мультиресурсы с конфигурацией api_mult. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__periodmat
        description: таблица Периоды материалов с конфигурацией api_periodmat. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__periodres
        description: таблица Периоды ресурсов с конфигурацией api_periodres. Названия колонок соответствуют кодам колонок из Spider Project
      - name: raw_spider__res
        description: таблица Ресурсы с конфигурацией api_res. Названия колонок соответствуют кодам колонок из Spider Project
  - name: dicts
    schema: public
    database: oup
    tables:
      - name: dict__rus_months
        description: справочник русских названий месяцев и кварталов, к которым относятся месяца
        columns:
        - name: num_month
          description: порядковый номер месяца
        - name: name_month
          description: название месяца на русском
        - name: quart
          description: сокращенное название квартала
      - name: dict__1c_objects_to_spider
        description: справочник названий объектов в 1С и Spider Project
        columns: 
          - name: territory_value
            description: уникальный код объекта в 1С
          - name: territory_name
            description: название объекта в 1С
          - name: territory_name_spider_project
            description: название объекта в Spider Project
  - name: excel
    schema: public
    database: oup
    tables:
      - name: raw__vdc_by_objects
        description: Контрактные ведомости из excel файлов загружаются в эту таблицу
        columns:
        - name: object
          description: объект строительства
  - name: 1c
    schema: 1c
    database: oup
    tables: 
      - name: 1_c__materials
        description: Раздел с указанием фактического расхода материалов из документа ЖУФВР
      - name: 1_c__norm_workload
        description: Талица, которая содержит нормативную трудоемкость выполненных работ по видам работ и ресурсам
      - name: 1_c__pikets
      - name: 1_c__technique_workers
        description: Эта таблица содержит фактические часы работы техники и рабочих. Является разделом (вкладкой) "Сводно по смене" из документа ЖУФВР
      - name: 1_c__works
        description: Эта таблица содержит названия и объемы выполненных работ
      - name: 1_c__zhufvr
models:
 - name: int__archive_by_month
   description: В этой таблице содержатся фактические показатели работ. Если длительность выполнения операции выходит за пределы какого-либо одного месяца, то эта длительность распределяется на несколько месяцев. Вес – это отношение длительности выполнения операции в пределах какого-либо месяца к общей длительности операции. Все показатели распределены по периодам (месяцам), а значения показателей определены с учетом веса. Распределение длительности выполнения операции по месяцам осуществлены при помощи рекурсивного запроса. Используется фильтр (WHERE "ZATRATY" IS NOT NULL or "PRIBYL" is not null or "SMRFull" is not null), чтобы оставить только ключевые значения.
   columns: 
     - name: smr_ss
       description: СМР собственные силы
     - name: smr_sp
       description: СМР субподрядчики
     - name: SMRFull
       description: стоимость проекта факт, т.е. сумма СМР собственные силы и СМР субподрядчики
     - name: ZATRATY
       description:  сумма всех затратных стоимостных составляющих согласно Нормам со знаком минус
     - name: PRIBYL
       description: разность между доходной частью и затратами
 - name: int__gant_by_month
   description: В этой таблице содержатся плановые данные операций. Если длительность выполнения операции выходит за пределы какого-либо одного месяца, то эта длительность распределяется на несколько месяцев. Вес – это отношение длительности выполнения операции в пределах какого-либо месяца к общей длительности операции. Все показатели распределены по периодам (месяцам), а значения показателей определены с учетом веса. Распределение длительности выполнения операции по месяцам осуществлены при помощи рекурсивного запроса.
   columns: 
     - name: smr_ss
       description: СМР собственные силы
     - name: smr_sp
       description: СМР субподрядчики
     - name: SMRFull
       description: стоимость проекта план, т.е. сумма СМР собственные силы и СМР субподрядчики
     - name: ZATRATY
       description: сумма всех затратных стоимостных составляющих согласно Нормам со знаком минус
     - name: PRIBYL
       description: разность между доходной частью и затратами
 - name: int__gant_start_transform
   description: Эта таблица применяется для расчета даты начала операции в плане. Если расчетная дата (окончание - длительность в днях) попадает на последний день месяца, то сдвигаем дату начала на первый день следующего месяца. Чтобы исключить операции связанные с операциями с типом ДПГ = Переключатель, добавлено условие (WHERE "Fin" is not null). Fin – дата и время окончания операции. 
   columns: 
     - name: dur_plan_d
       description: Длительность, Дни [План]
     - name: start_year
       description: Год начала в формате числа
     - name: start_month
       description: Месяц начала в формате числа 

 - name: int__vdc_by_objects
   description: Эта таблица содержит ВДЦ всех действующих объектов. Данными для этой таблицы являются "сырые" данные из таблицы raw__vdc_by_objects. Столбец "Позиция из КВ" применятся для наглядной демонстрации названии работы вместе с номером контрактной позиции.
   columns: 
     - name: "СМР П"
       description: Цена работы (всего) из контрактной ведомости. Примечание':' в зависимости от объектов строительства название в контрактной ведомости может отличаться
     - name: "Позиция из КВ"
       description: объединение столбцов "Шифр единичной расценки" и "Наименование работ и затрат", и между ними 4 пробела. Применяется для наглядной демонстрации шифра и названия работы
     - name: unique_test
       description: объединение столбцов "Шифр единичной расценки" и "object", и между ними 4 пробела. Применяется в тесте на поиск повторяющихся контрактных позиций. Применены два теста':' 1) unique - значения столбца должны быть уникальными и 2) not_null - не NULL (не пустые)
       tests: 
         - unique 
         - not_null
 - name: mart__gant_archive_by_month
   description: В этой таблице (витрине) объединяются фактические и плановые показатели работ. Используются различные условия для того, чтобы привести значения пользовательских полей к требованиям Методологии (пользовательские поля ':' Силы реализации, Конструктив).
   columns:
     - name: ZATRATY 
       description: затратная часть
     - name: PRIBYL
       description: прибыль
     - name: SMRFull
       description: доходная часть
     - name: s_month
       description: месяц начала операции. С помощью условия добавлен 0 (ноль) перед номерами месяцев, состоящих из одной цифры. Это необходимо для построения графиков в Superset 
     - name: smr_type
       description: тип СМР - факт или план
     - name: Name
       description: название операции 
     - name: Ispol
       description: Пользовательское поле Исполнитель 
     - name: IspolUch
       description: Пользовательское поле Исполнитель [Строительные участки]
     - name: Силы реализации
       description: Пользовательское поле 
     - name: SNT_Knstr
       description: Пользовательское поле Конструктив
     - name: SNT_KnstrE
       description: Пользовательское поле Конструктивный элемент
     - name: SNT_TypeKnstrE
       description: Пользовательское поле Тип конструктивного элемента
     - name: SNT_Obj
       description: Пользовательское поле Объект строительства
     - name: Num_Con
       description: Пользовательское поле № п/п по контрактной ведомости
     - name: Конструктив
       description: после применения условия остаются 3 значения – Земляное полотно, Дорожная одежда и Прочие работы, так как в форме Ф1 Наряд-задания показаны эти 3 конструктива
